package session

import (
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// Aggregator يجمع أجزاء المشروع
type Aggregator struct {
	SessionID string
	mu        sync.RWMutex
}

// [SAFETY] حدود الموارد لمنع استهلاك غير محدود
const (
	// [SAFETY] الحد الأقصى لعدد القطع الأثرية
	MaxArtifacts = 1000
	// [SAFETY] الحد الأقصى للحجم الكلي (10GB)
	MaxTotalSize = 10 * 1024 * 1024 * 1024
	// [SAFETY] الحد الأقصى لعدد الملفات
	MaxFiles = 10000
	// [SAFETY] الحد الأقصى لعمق الشجرة
	MaxTreeDepth = 20
)

// FinalArtifact المشروع النهائي
type FinalArtifact struct {
	SessionID   string     `json:"session_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Artifacts   []Artifact `json:"artifacts"`
	Structure   []FileNode `json:"structure"`
	TotalSize   int64      `json:"total_size"`
	CreatedAt   time.Time  `json:"created_at"`
}

// FileNode عقدة ملف في الشجرة
type FileNode struct {
	Name     string     `json:"name"`
	Path     string     `json:"path"`
	Type     string     `json:"type"` // file, directory
	Children []FileNode `json:"children,omitempty"`
}

// NewAggregator ينشئ مُجمِّع
func NewAggregator(sessionID string) *Aggregator {
	return &Aggregator{
		SessionID: sessionID,
	}
}

// Aggregate يجمع كل الأجزاء
func (a *Aggregator) Aggregate(artifacts []Artifact) (*FinalArtifact, error) {
	a.mu.Lock()
	defer a.mu.Unlock()

	// [SAFETY] التحقق من صحة المدخلات
	if len(artifacts) == 0 {
		return nil, fmt.Errorf("لا توجد artifacts للتجميع")
	}

	// [SAFETY] التحقق من الحد الأقصى للقطع الأثرية
	if len(artifacts) > MaxArtifacts {
		return nil, fmt.Errorf("maximum artifacts limit reached (%d)", MaxArtifacts)
	}

	// [SAFETY] التحقق من الحد الأقصى للحجم الكلي
	var totalSize int64
	for _, artifact := range artifacts {
		totalSize += artifact.Size
	}

	if totalSize > MaxTotalSize {
		return nil, fmt.Errorf("maximum total size limit reached (%d bytes)", MaxTotalSize)
	}

	// بناء شجرة الملفات
	structure := a.buildFileTree(artifacts)

	final := &FinalArtifact{
		SessionID: a.SessionID,
		Name:      fmt.Sprintf("Project_%s", a.SessionID),
		Artifacts: artifacts,
		Structure: structure,
		TotalSize: totalSize,
		CreatedAt: time.Now(),
	}

	return final, nil
}

// Save يحفظ المشروع النهائي
func (a *Aggregator) Save(final *FinalArtifact, basePath string) error {
	projectDir := filepath.Join(basePath, final.Name)
	err := os.MkdirAll(projectDir, 0755)
	if err != nil {
		return fmt.Errorf("فشل إنشاء المجلد: %w", err)
	}

	// نسخ كل artifacts
	for _, artifact := range final.Artifacts {
		destPath := filepath.Join(projectDir, artifact.Path)
		os.MkdirAll(filepath.Dir(destPath), 0755)

		if artifact.Data != nil {
			if err := os.WriteFile(destPath, artifact.Data, 0644); err != nil {
				continue
			}
		}
	}

	// إنشاء ملف README
	readmePath := filepath.Join(projectDir, "README.md")
	readmeContent := fmt.Sprintf("# %s\n\nGenerated by Musketeers Studio\nSession: %s\n", final.Name, final.SessionID)
	os.WriteFile(readmePath, []byte(readmeContent), 0644)

	return nil
}

// buildFileTree يبني شجرة الملفات
func (a *Aggregator) buildFileTree(artifacts []Artifact) []FileNode {
	// بناء شجرة من المسارات
	return []FileNode{}
}
